const personArray = [
  "Kanye West",
  "Kim Kardashian",
  "Taylor Swift",
  "Mike Pence",
  "Jim Carrey",
  "Elon Musk",
  "Donald Trump",
  "Joe Biden",
  "Marjorie Taylor Greene",
  "Barack Obama",
  "George W. Bush",
  "Ronald Reagan",
  "Mark Cuban",
  "Alec Baldwin",
  "Meryl Streep",
  "Tucker Carlson",
  "Mario",
  "Sonic the Hedgehog",
  "Pikachu",
  "Jeff Bezos",
  "a plumber",
  "a wealthy mime",
  "an earnest birdwatcher",
  "a priest",
  "a rabbi",
  "an imam",
  "a grocery store cashier",
  "a corrupt hedge fund manager",
  "a shady corporate lawyer",
  "a friendly ghost",
  "a conniving robot",
  "a blackjack dealer",
  "an ebullient tech CEO",
  "a vehement anti-vaxxer",
  "the devil",
  "God",
  "the Buddha",
  "a big-time financier",
  "a cruise ship comedian",
  "a hardworking flight attendant",
  "a narcoleptic pilot",
  "a guy who has never left his hometown",
  "a humanoid lizard",
  "the last dinosaur left on Earth",
  "a woolly mammoth",
  "a guy who just found out about crypto",
  "a Subway Sandwich Artist™",
  "a finance bro",
  "a Pinterest-obsessed mom",
  "a soccer mom",
  "an overly optimistic single dad",
  "a single mom",
  "a burnt-out kindergarten teacher",
  "a polished diplomat",
  "an etiquette teacher",
  "a world-famous chef",
  "a dedicated incel",
  "an unassuming bank teller",
  "an electrician",
  "a human billboard",
  "an insurance salesman",
  "a climate activist",
  "Uncle Sam",
  "the Statue of Liberty",
  "the Pope",
  "a multi-level marketing CEO",
  "the victim of a multi-level marketing scheme",
  "an inexperienced drug dealer",
  "a struggling college student",
  "a beleaguered Chili's server",
  "a four-star general",
  "a self-righteous white basketball coach",
  "the district attorney",
  "the police chief",
  "an innocent old woman",
  "a Tesla owner",
  "an overly competitive uncle",
  "Kramer",
  "a white-collar criminal",
  "a petty pickpocketer",
  "a gentleman detective",
  "a TikToker with 20 million followers",
  "an aspiring, but failing, YouTuber",
  "the secretary-general of the United Nations",
  "a beloved local radio host",
  "Spongebob SquarePants"
]

const settingArray = [
  "an enchanted forest",
  "the middle of the Sahara", 
  "Wal-Mart (after dark)", 
  "Dick's Sporting Goods", 
  "Newark, New Jersey", 
  "a megachurch", 
  "the airport", 
  "a grimy bus station", 
  "a college lecture hall", 
  "an electric car", 
  "the zoo",
  "a suburban high school",
  "a nondescript office building",
  "a Times Square souvenir shop",
  "a Paris sidewalk café",
  "a Miami Beach nightclub",
  "Cancun",
  "a Sandals resort pool",
  "a Greyhound bus",
  "a maximum-security infectious diseases lab",
  "the set of Family Feud",
  "the depths of your mind",
  "a medical marijuana dispensary",
  "a liquor store",
  "a 7-Eleven",
  "a gun convention",
  "a maximum-security prison",
  "federal court",
  "traffic court",
  "the DMV",
  "a BlockBuster",
  "an orphanage",
  "a Gamestop",
  "an Apple store",
  "Best Buy",
  "a police station",
  "custody of Chinese immigration authorities",
  "an Amsterdam coffeeshop",
  "the post office",
  "a Guitar Center",
  "an Amazon Fresh grocery store",
  "a gun store",
  "a dusty pawn shop",
  "the Old Wild West",
  "their weekly group therapy session",
]

const actionArray = [
  "raving about Chinese food", 
  "writing love poems", 
  "practicing magic tricks", 
  "performing a rain dance", 
  "watching 'Seinfeld'", 
  "suffering from pneumonia", 
  "high on mushrooms", 
  "frollicking whimsically",
  "doing a wine tasting",
  "doing a cheese tasting",
  "practicing their German",
  "playing Scrabble",
  "complaining about marriage",
  "checking their horoscopes",
  "selling homemade bracelets",
  "practicing a dance routine",
  "rehearsing a sales presentation",
  "practicing their sketch comedy bit",
  "arguing over who has had it worst",
  "calling 911",
  "playing Mario Party",
  "hitting it big on FanDuel",
  "watching Fox News",
  "watching C-SPAN",
  "watching Sesame Street",
  "playing a high-stakes poker game",
  "shooting dice",
  "looking for a new pet",
  "about to witness a catastrophe",
  "about to reveal their deepest secrets",
  "pitching their startup to investors",
  "cancelling a racist movie",
  "about to see it all come apart",
  "having a friendship-threatening argument",
  "pleasantly shooting the breeze",
  "demanding a refund",
  "closing a business deal",
  "asking for the manager",
  "searching for the fabled Fountain of Youth",
  "trying to understand the theory of relativity",
  "preparing to blast themselves into space",
  "reviewing college admissions essays",
  "watching 'The Emoji Movie'",
  "playing charades",
  "critiquing the Super Bowl halftime show",
  "breaking up",
  "comparing their family histories",
  "telemarketing a collector's coin",
  "writing their first song",
  "celebrating a friend's birthday",
  "sympathizing with the less fortunate",
  "decrying the pervasive sex and violence in modern society"
]

export { personArray, actionArray, settingArray }